import { useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { postAPI, aiAPI } from '../../services/api.js';
import toast from 'react-hot-toast';
import {
  PhotoIcon, XMarkIcon, ArrowUpTrayIcon, SparklesIcon
} from '@heroicons/react/24/outline';

export default function CreatePostPage() {
  const navigate = useNavigate();
  const fileRef = useRef();

  const [caption, setCaption] = useState('');
  const [media, setMedia] = useState(null);
  const [mediaPreview, setMediaPreview] = useState('');
  const [hashtags, setHashtags] = useState([]);
  const [loading, setLoading] = useState(false);
  const [isAiLoading, setIsAiLoading] = useState(false);
  const [aiStatus, setAiStatus] = useState('idle');
  const [lastUserPrompt, setLastUserPrompt] = useState('');

  const handleSmartGenerate = async () => {
    setIsAiLoading(true);
    setAiStatus('generating');
    try {
      const promptToUse = aiStatus === 'regenerated' ? lastUserPrompt : caption;
      if (aiStatus !== 'regenerated') {
        setLastUserPrompt(caption);
      }
      const { data } = await aiAPI.suggestCaption({ topic: promptToUse || 'A wonderful day' });
      if (data.success) {
        setCaption(data.data.caption);
        setAiStatus('regenerated');
        toast.success('Generated successfully!');
      }
    } catch (error) {
      toast.error('Failed to generate content');
      setAiStatus('idle');
    } finally {
      setIsAiLoading(false);
    }
  };

  const handleGenerateHashtags = async () => {
    setIsAiLoading(true);
    try {
      const { data } = await aiAPI.generateHashtags({ text: caption.trim() || 'a general engaging social media post' });
      console.log('Hashtags response:', data);
      if (data && data.success && data.data && data.data.hashtags && data.data.hashtags.length > 0) {
        setHashtags(data.data.hashtags);
        const tagsString = data.data.hashtags.join(' ');
        setCaption(prev => prev + (prev.trim() ? '\n\n' : '') + tagsString);
        toast.success('Hashtags generated and added!');
      } else {
        toast.error('No hashtags could be generated by AI');
      }
    } catch (error) {
      console.error('Hashtags error:', error);
      toast.error(error?.response?.data?.message || error.message || 'Failed to generate hashtags');
    } finally {
      setIsAiLoading(false);
    }
  };

  const handleMediaChange = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    if (file.size > 50 * 1024 * 1024) return toast.error('File must be under 50MB (Max ~10 min video)');
    setMedia(file);
    setMediaPreview(URL.createObjectURL(file));
  };

  const removeMedia = () => {
    setMedia(null);
    setMediaPreview('');
    if (fileRef.current) fileRef.current.value = '';
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!caption && !media) return toast.error('Add a caption or media to your post');

    setLoading(true);
    try {
      const formData = new FormData();
      if (caption) formData.append('caption', caption);
      if (media) formData.append('image', media);
      if (hashtags.length > 0) formData.append('hashtags', JSON.stringify(hashtags));

      await postAPI.createPost(formData);
      toast.success('Post published!');
      navigate('/feed');
    } catch (error) {
      toast.error(error.response?.data?.message || 'Failed to create post');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-2xl mx-auto px-4 py-8 animate-slide-up">
      <div className="flex items-center gap-3 mb-8">
        <h1 className="text-3xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-primary-600 to-secondary-500 animate-fade-in tracking-tight">Create Post</h1>
        <div className="h-1 flex-1 bg-gradient-to-r from-primary-100 to-transparent rounded-full opacity-50"></div>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        {/* Media upload */}
        <div className="card-glass p-5 hover-3d border-primary-50">
          {mediaPreview ? (
            <div className="relative group">
              {media?.type?.startsWith('video') ? (
                <video src={mediaPreview} controls className="w-full max-h-[500px] bg-black/5 object-contain rounded-2xl shadow-inner" />
              ) : (
                <img src={mediaPreview} alt="Preview" className="w-full max-h-[500px] object-cover rounded-2xl shadow-inner transition-transform duration-500" />
              )}
              <div className="absolute inset-0 rounded-2xl ring-4 ring-primary-500/0 group-hover:ring-primary-500/20 transition-all duration-300 pointer-events-none"></div>
              <button type="button" onClick={removeMedia}
                className="absolute top-4 right-4 bg-white/90 backdrop-blur-sm text-red-500 rounded-full p-2 hover:bg-red-500 hover:text-white transition-all duration-300 shadow-lg hover:scale-110 hover:rotate-90">
                <XMarkIcon className="w-5 h-5" />
              </button>
            </div>
          ) : (
            <button type="button" onClick={() => fileRef.current?.click()}
              className="w-full border-2 border-dashed border-primary-200/60 rounded-2xl p-14 flex flex-col items-center justify-center text-gray-400 hover:border-primary-400 hover:text-primary-500 hover:bg-primary-50/30 transition-all duration-300 group shadow-sm hover:shadow-md">
              <div className="bg-primary-100/50 p-4 rounded-full mb-4 group-hover:scale-110 group-hover:-translate-y-2 transition-all duration-300">
                <PhotoIcon className="w-10 h-10 text-primary-500" />
              </div>
              <p className="font-semibold text-lg text-gray-700">Click to upload photo or video</p>
              <p className="text-sm mt-2 text-gray-400/80 font-medium tracking-wide">JPG, PNG, MP4 • Max 50MB</p>
            </button>
          )}
          <input ref={fileRef} type="file" accept="image/*,video/*" className="hidden" onChange={handleMediaChange} />
        </div>

        {/* Caption */}
        <div className="card-glass p-5 hover-3d border-primary-50">
          <textarea
            value={caption}
            onChange={(e) => {
              setCaption(e.target.value);
              if (aiStatus === 'regenerated') setAiStatus('idle');
            }}
            placeholder="Write a captivating caption, or type a prompt like 'good morning shayari' and click AI Generate ✨"
            className="w-full resize-none bg-transparent text-gray-800 placeholder-gray-400/70 focus:outline-none text-lg leading-relaxed min-h-[120px]"
            maxLength={2000}
          />
          <div className="flex items-center justify-between mt-3 pt-3 border-t border-gray-100/60">
            <div className="flex gap-2">
              <span className="text-xs font-semibold px-2 py-1 bg-gray-100 text-gray-500 rounded-md">Text</span>
              {hashtags.length > 0 && <span className="text-xs font-semibold px-2 py-1 bg-primary-50 text-primary-600 rounded-md">{hashtags.length} Tags</span>}
            </div>
            <span className={`text-xs font-bold transition-colors ${caption.length > 1900 ? 'text-orange-500' : 'text-gray-400'}`}>
              {caption.length} <span className="opacity-50">/ 2000</span>
            </span>
          </div>

          {/* AI Tools */}
          <div className="flex flex-wrap gap-3 mt-4">
            <button type="button" onClick={handleSmartGenerate} disabled={isAiLoading}
              className="flex items-center gap-1.5 text-sm font-semibold px-4 py-2 bg-gradient-to-r from-violet-100 to-fuchsia-100 text-violet-700 hover:from-violet-200 hover:to-fuchsia-200 rounded-xl transition-all shadow-sm hover:shadow-md active:scale-95 border border-violet-200/50 whitespace-nowrap">
              <SparklesIcon className={`w-4 h-4 ${isAiLoading ? 'animate-spin' : ''}`} /> 
              {aiStatus === 'generating' ? 'Writing...' : aiStatus === 'regenerated' ? '🔄 Try Another' : caption.trim() ? '✨ Generate from text' : '✨ Generate AI Caption'}
            </button>
            <button type="button" onClick={handleGenerateHashtags} disabled={isAiLoading}
              className="flex items-center gap-1.5 text-sm font-semibold px-4 py-2 bg-gradient-to-r from-blue-100 to-cyan-100 text-blue-700 hover:from-blue-200 hover:to-cyan-200 rounded-xl transition-all shadow-sm hover:shadow-md active:scale-95 border border-blue-200/50 whitespace-nowrap">
              <SparklesIcon className={`w-4 h-4 ${isAiLoading ? 'animate-pulse' : ''}`} /> 
              {isAiLoading && aiStatus === 'idle' ? 'Analyzing...' : 'Auto Hashtags'}
            </button>
          </div>
        </div>

        {/* Submit */}
        <div className="flex gap-4 pt-2">
          <button type="button" onClick={() => navigate(-1)} className="btn-secondary flex-1 py-3.5 text-lg hover:shadow-lg">
            Cancel
          </button>
          <button type="submit" disabled={loading || (!caption && !media)} className="btn-primary flex-1 flex items-center justify-center gap-2 py-3.5 text-lg shadow-[0_10px_20px_-10px_rgba(var(--tw-colors-primary-500),0.5)]">
            <ArrowUpTrayIcon className={`w-5 h-5 ${loading ? 'animate-bounce' : 'group-hover:-translate-y-1 transition-transform'}`} />
            {loading ? 'Publishing...' : 'Publish Post'}
          </button>
        </div>
      </form>
    </div>
  );
}